### PR TITLE
updated money legos

### PR DESCRIPTION
**Pull request by kendricktan**

### CODE REVIEW

**Comment by adrianmcli** [comment]
I agree that this is the right way to store it:

```js
const maker = {
  proxyRegistry: {
    address: {
      [networkIds.mainnet]: "0x4678f0a6958e4D2Bc4F1BAF7Bc52E8F3564f3fE4"
    },
    abi: makerProxyRegistryAbi,
  },
};
```

But for the outward-facing API, I think the network should probably be decided at the "root" of the tree. For example:

```js
// legos.js
import { mainnet, ropsten } from "money-legos";

// store legos in global app state
setLegos(isTestnet ? ropsten : mainnet);
```

```js
// MyComponent.js
import { maker, compound } from "../legos"

const makerProxy = new ethers.Contract(
  maker.proxyRegistry.address,
  maker.proxyRegistry.abi,
  wallet,
);
```

This way you don't need to think about what network you are on, once you're deep in the code. Usually it's something that you think about at the top of your app and then you assume you're in the same network for the rest of the app.

In either case, this comment is probably out of scope because we're not publishing this yet. Just wanted to bounce ideas off of you.

**Comment by kendricktan** [comment]
I like that idea, perhaps we can do somethibg like

```javascript 
Const { getLegos, networkIds} = ("money-legos") 

Const legos = getLegos(networkIds.mainnet)
```

**Comment by adrianmcli** [comment]
I likkkeeeeee it. That way, they can do this whenever the network changes:

```js
provider.on('chainChanged', (chainId) => {
  const legos = getLegos(chainId)
  setLegos(legos)
})

// wheeeeee, I'm drunk
```

**Comment by adrianmcli** [comment]
Also, TIL: `networkChanged` is deprecated in favour of `chainChanged`: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md#chainchanged

**Comment by kendricktan** [comment]
Cool, I've added that feature 

```javascript
const { getLegos, networkIds } = ("money-legos") 

const legos = getLegos(networkIds.mainnet)
```

https://github.com/studydefi/dedge/blob/master/packages/smart-contracts/test/testDedgeGeneralManager.ts#L18

**Pull request merged**
